### PR TITLE
Add external tests extensions

### PR DESCRIPTION
**Pull request by dlopes7**
This PR adds three extensions that report data using the external synthetic API.

* ping
* port
* dns

FYI @Mike997

### CODE REVIEW

**Comment by Mike997** [comment]
My fault, sorry! 👍

**Comment by dlopes7** [comment]
I pushed the change, but I named the folder activegate-extensions instead

**Comment by myieye** [comment]
We've already merged code that expects the folder to be called "active-gate-extensions" and our PM was happy with that name, so please use that instead.
Do you think that "activegate-extensions" is a significant improvement?

**Comment by dlopes7** [comment]
Not significant, I just never seen it used like that before, but I don't mind, will push the change

**Comment by myieye** [comment]
@dlopes7 Thanks :)
external was recently renamed to third-party, but I'm not sure if it would be worth the effort to rename these 🤔. How much effort would that be?

**Comment by dlopes7** [comment]
@myieye I can change that no problem

**Comment by myieye** [comment]
@dlopes7  OK. I'll let you decide how thorough you want to be 😉 
image

**Comment by dlopes7** [comment]
Those classes match the model names and fields from the API, I'll rename them accordingly, I believe it is "3rdParty" now

**Comment by dlopes7** [comment]
I will unfortunately need to use ThirdParty because it starts with a number

**Comment by myieye** [comment]
@dlopes7 I like "ThirdParty" more anyway 😄 

So you'll rename:
- Code symbols
- folders
- the plugin zip

Is that right?

**Comment by myieye** [comment]
Also, what's the reason you didn't include the proxy or mssql extensions?

**Comment by dlopes7** [comment]
Yes I will replace every occurrence of the word external

**Comment by dlopes7** [comment]
The current MSSQL extension is using pyodbc, which means it has external dependencies on the AG machine, so it is not as "plug and play". We will add another version in the future, that uses `pymssql` or `ctds`  instead, I assume this is not urgent and can be done in another PR.

I'll let @Mike997 comment on the Proxy one, I believe there is similar functionality OOTB in Dynatrace

**Comment by Mike997** [comment]
Proxy was created when Synthetic tests couldn’t set a specific proxy per test, only per ActiveGate. Now that the proxy can be set per test we don’t need that extension anymore.

**Comment by dlopes7** [comment]
@dyaigs anything else we need to change to have this one merged?

**Pull request merged**
