### PR TITLE
rebuilt existing version with older glib versions

### PR DESCRIPTION
**Pull request by Dynatrace-James-Kitson**
Support case was opened due to inability to run this on Oracle 7.9 due to it being built with glib 2.18 while that OS has glib 2.17.

This is just a rebuild of the same version with the older glib version so that it can run on this older (still supported) ActiveGate OS and still run on newer versions. It was tested in the older version as well as a newer OS.

### CODE REVIEW

**Comment by dlopes7** [comment]
LGTM!

@myieye can we merge this one?

**Comment by dlopes7** [comment]
Maybe @floriangeigl

**Comment by floriangeigl** [comment]
sorry - I don't have any power here ;) ...and also no idea what this is about :)

**Comment by Dynatrace-James-Kitson** [comment]
Have some other changes to make. Will combine with this in a new PR.

**Pull request closed without merging**
