### PR TITLE
Synthetic Linux Commands

### PR DESCRIPTION
**Pull request by radu-stefan-dt**
A third party synthetic ActiveGate extension for running commands on remote Linux hosts.

### CODE REVIEW

**Comment by myieye** [comment]
@radu-stefan-dt Can you find someone to review this?

**Comment by radu-stefan-dt** [comment]
@Dynatrace-James-Kitson - can you review this?

**Review by Dynatrace-James-Kitson — APPROVED** [review]
Reviewed and ran over the different scenarios. Everything looks good.

**Comment by Dynatrace-James-Kitson** [comment]
> @Dynatrace-James-Kitson - can you review this?

Reviewed but it shows I don't have write access so can't merge it in.

**Comment by radu-stefan-dt** [comment]
@myieye - when you get a chance, please merge if you are happy with the review

**Comment by myieye** [comment]
@Dynatrace-James-Kitson Thanks for reviewing 👍

**Pull request merged**
